/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.RasJimenezBlai.vista;

import edu.ub.prog2.RasJimenezBlai.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author blair
 */
public class FrmAfegirFitxerMultimedia extends javax.swing.JDialog {
    Controlador controlador;
    
    /**
     * Creates new form FrmAfegirFitxerMultimedia
     */
    public FrmAfegirFitxerMultimedia(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        panellAudio.setVisible(false);
        panellImatge.setVisible(false);
        panellVideo.setVisible(false);
        panellAudio.setEnabled(false);
        panellImatge.setEnabled(false);
        panellVideo.setEnabled(false);
        panellSeleccionar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccepta = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        activarVideo = new javax.swing.JRadioButton();
        activarAudio = new javax.swing.JRadioButton();
        activarImatge = new javax.swing.JRadioButton();
        panellVideo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomVideo = new javax.swing.JTextField();
        txtFps = new javax.swing.JTextField();
        txtCodec = new javax.swing.JTextField();
        txtAmplada = new javax.swing.JTextField();
        txtAlcada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDuradaVideo = new javax.swing.JTextField();
        panellImatge = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomImatge = new javax.swing.JTextField();
        txtAmpladaImatge = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAlcadaImatge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panellAudio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNomAudio = new javax.swing.JTextField();
        txtNomCodec = new javax.swing.JTextField();
        txtNomDurada = new javax.swing.JTextField();
        txtNomKpbs = new javax.swing.JTextField();
        txtCamiCaratula = new javax.swing.JTextField();
        btnAfegirImatge = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        panellSeleccionar = new javax.swing.JPanel();
        txtCami = new javax.swing.JTextField();
        btnSelecciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(809, 495));

        btnAccepta.setText("Accepta");
        btnAccepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptaActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Quin tipus de fitxer vols Afegir a la Biblioteca?");

        activarVideo.setText("Video");
        activarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarVideoActionPerformed(evt);
            }
        });

        activarAudio.setText("Audio");
        activarAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarAudioActionPerformed(evt);
            }
        });

        activarImatge.setText("Imatge");
        activarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarImatgeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom:");

        jLabel5.setText("Durada:");

        jLabel6.setText("Alçada:");

        jLabel7.setText("Amplada:");

        jLabel8.setText("FPS:");

        jLabel15.setText("Video");

        jLabel18.setText("Codec:");

        javax.swing.GroupLayout panellVideoLayout = new javax.swing.GroupLayout(panellVideo);
        panellVideo.setLayout(panellVideoLayout);
        panellVideoLayout.setHorizontalGroup(
            panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellVideoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellVideoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panellVideoLayout.createSequentialGroup()
                        .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFps))
                            .addGroup(panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(txtAmplada))
                            .addGroup(panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlcada, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .addGroup(panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomVideo))
                            .addGroup(panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuradaVideo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panellVideoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodec)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        panellVideoLayout.setVerticalGroup(
            panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellVideoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellVideoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuradaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlcada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellVideoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panellVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel11.setText("Nom:");

        jLabel13.setText("Amplada:");

        jLabel17.setText("Imatge");

        jLabel14.setText("Alçada:");

        javax.swing.GroupLayout panellImatgeLayout = new javax.swing.GroupLayout(panellImatge);
        panellImatge.setLayout(panellImatgeLayout);
        panellImatgeLayout.setHorizontalGroup(
            panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellImatgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellImatgeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomImatge))
                    .addGroup(panellImatgeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmpladaImatge))
                    .addGroup(panellImatgeLayout.createSequentialGroup()
                        .addGroup(panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(panellImatgeLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlcadaImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panellImatgeLayout.setVerticalGroup(
            panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellImatgeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addGroup(panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNomImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmpladaImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(panellImatgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlcadaImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel3.setText("Nom:");

        jLabel9.setText("Codec");

        jLabel10.setText("Durada:");

        jLabel12.setText("Kpbs:");

        btnAfegirImatge.setText("Selecciona la Imatge");
        btnAfegirImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirImatgeActionPerformed(evt);
            }
        });

        jLabel16.setText("Audio");

        javax.swing.GroupLayout panellAudioLayout = new javax.swing.GroupLayout(panellAudio);
        panellAudio.setLayout(panellAudioLayout);
        panellAudioLayout.setHorizontalGroup(
            panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellAudioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panellAudioLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomAudio))
                        .addGroup(panellAudioLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(14, 14, 14)
                            .addComponent(txtNomDurada))
                        .addGroup(panellAudioLayout.createSequentialGroup()
                            .addComponent(btnAfegirImatge)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCamiCaratula, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGroup(panellAudioLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomCodec))
                        .addGroup(panellAudioLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomKpbs)))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellAudioLayout.setVerticalGroup(
            panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellAudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamiCaratula)
                    .addComponent(btnAfegirImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNomDurada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panellAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNomKpbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSelecciona.setText("Selecciona");
        btnSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellSeleccionarLayout = new javax.swing.GroupLayout(panellSeleccionar);
        panellSeleccionar.setLayout(panellSeleccionarLayout);
        panellSeleccionarLayout.setHorizontalGroup(
            panellSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelecciona)
                .addGap(19, 19, 19))
        );
        panellSeleccionarLayout.setVerticalGroup(
            panellSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecciona))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panellSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panellVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panellAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(panellImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(activarVideo)
                                .addGap(233, 233, 233)
                                .addComponent(activarAudio)
                                .addGap(197, 197, 197)
                                .addComponent(activarImatge)
                                .addGap(85, 85, 85)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(btnAccepta)
                .addGap(163, 163, 163)
                .addComponent(btnCancela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activarVideo)
                    .addComponent(activarAudio)
                    .addComponent(activarImatge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panellSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panellImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panellAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panellVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepta)
                    .addComponent(btnCancela))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionaActionPerformed
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
        //Obtenim el fitxer
        fitxer=seleccio.getSelectedFile();
        //Posem la ruta del fitxer al quadre de text
        txtCami.setText(fitxer.toString());
        }
    }//GEN-LAST:event_btnSeleccionaActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void activarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarVideoActionPerformed
        panellVideo.setLocation(200, 100);
        panellSeleccionar.setVisible(true);
        panellVideo.setEnabled(true);
        panellVideo.setVisible(true);
        panellAudio.setVisible(false);
        panellAudio.setEnabled(false);
        activarAudio.setSelected(false);
        panellImatge.setEnabled(false);
        panellImatge.setVisible(false);
        activarImatge.setSelected(false);
    }//GEN-LAST:event_activarVideoActionPerformed

    private void activarAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarAudioActionPerformed
        panellSeleccionar.setVisible(true);
        panellAudio.setVisible(true);
        panellAudio.setEnabled(true);
        activarVideo.setSelected(false);
        panellVideo.setEnabled(false);
        panellVideo.setVisible(false);
        panellImatge.setEnabled(false);
        panellImatge.setVisible(false);
        activarImatge.setSelected(false);
    }//GEN-LAST:event_activarAudioActionPerformed

    private void activarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarImatgeActionPerformed
        panellSeleccionar.setVisible(true);
        panellAudio.setVisible(false);
        activarAudio.setSelected(false);
        panellVideo.setVisible(false);
        activarVideo.setSelected(false);
        panellAudio.setEnabled(false);
        panellVideo.setEnabled(false);
        panellImatge.setVisible(true);
        panellImatge.setEnabled(true);
        
    }//GEN-LAST:event_activarImatgeActionPerformed

    private void btnAcceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptaActionPerformed

        if (activarAudio.isSelected()) {
            if (txtCami.getText().equals("") || txtCamiCaratula.getText().equals("") || txtNomAudio.getText().equals("") || txtNomCodec.getText().equals("") || txtNomDurada.getText().equals("") || txtNomKpbs.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,"Completa tots els camps abans d'afegir l'Audio!","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                float durada = Float.parseFloat(txtNomDurada.getText());
                int kpbs = Integer.parseInt(txtNomKpbs.getText());
                try {
                    controlador.afegirAudio(txtCami.getText(), txtCamiCaratula.getText(), txtNomAudio.getText(), txtNomCodec.getText(), durada, kpbs);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar afegir un Audio: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            
            this.dispose();
            }
        }
        
        if (activarVideo.isSelected()) {
            if (txtCami.getText().equals("") || txtDuradaVideo.getText().equals("") || txtNomVideo.getText().equals("") || txtCodec.getText().equals("") || txtAlcada.getText().equals("") || txtAmplada.getText().equals("")|| txtFps.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,"Completa tots els camps abans d'afegir el Video","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                float durada = Float.parseFloat(txtDuradaVideo.getText());
                int alcada = Integer.parseInt(txtAlcada.getText());
                int amplada = Integer.parseInt(txtAmplada.getText());
                float fps = Float.parseFloat(txtFps.getText());
                try {
                    controlador.afegirVideo(txtCami.getText(), txtNomVideo.getText(), txtNomCodec.getText(), durada, alcada, amplada, fps);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar afegir un Video: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
            this.dispose();
            }
        }
        
        if (activarImatge.isSelected()) {
            if (txtCami.getText().equals("") || txtNomImatge.getText().equals("") || txtAlcadaImatge.getText().equals("") || txtAmpladaImatge.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,"Completa tots els camps abans d'afegir l'Imatge","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                int alcada = Integer.parseInt(txtAlcadaImatge.getText());
                int amplada = Integer.parseInt(txtAmpladaImatge.getText());
                try {
                    controlador.afegirImatge(txtCami.getText(), txtNomImatge.getText(), alcada, amplada);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar afegir una imatge: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAcceptaActionPerformed

    private void btnAfegirImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirImatgeActionPerformed
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
        //Obtenim el fitxer
        fitxer=seleccio.getSelectedFile();
        //Posem la ruta del fitxer al quadre de text
        txtCamiCaratula.setText(fitxer.toString());
        }
    }//GEN-LAST:event_btnAfegirImatgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activarAudio;
    private javax.swing.JRadioButton activarImatge;
    private javax.swing.JRadioButton activarVideo;
    private javax.swing.JButton btnAccepta;
    private javax.swing.JButton btnAfegirImatge;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSelecciona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panellAudio;
    private javax.swing.JPanel panellImatge;
    private javax.swing.JPanel panellSeleccionar;
    private javax.swing.JPanel panellVideo;
    private javax.swing.JTextField txtAlcada;
    private javax.swing.JTextField txtAlcadaImatge;
    private javax.swing.JTextField txtAmplada;
    private javax.swing.JTextField txtAmpladaImatge;
    private javax.swing.JTextField txtCami;
    private javax.swing.JTextField txtCamiCaratula;
    private javax.swing.JTextField txtCodec;
    private javax.swing.JTextField txtDuradaVideo;
    private javax.swing.JTextField txtFps;
    private javax.swing.JTextField txtNomAudio;
    private javax.swing.JTextField txtNomCodec;
    private javax.swing.JTextField txtNomDurada;
    private javax.swing.JTextField txtNomImatge;
    private javax.swing.JTextField txtNomKpbs;
    private javax.swing.JTextField txtNomVideo;
    // End of variables declaration//GEN-END:variables
}
