/**
 *
 * @author Blai Ras Jimenez
 */
package edu.ub.prog2.RasJimenezBlai.vista;

import edu.ub.prog2.RasJimenezBlai.controlador.Controlador;
import edu.ub.prog2.RasJimenezBlai.model.AlbumFitxersMultimedia;
import edu.ub.prog2.RasJimenezBlai.model.FitxerMostrable;
import edu.ub.prog2.RasJimenezBlai.model.FitxerMultimedia;
import edu.ub.prog2.RasJimenezBlai.model.FitxerReproduible;
import edu.ub.prog2.utils.AplicacioException;
import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author blair
 */
public class AplicacioUB4 extends javax.swing.JFrame {
    Controlador controlador;
    /**
     * Creates new form AplicacioUB4
     */
    public AplicacioUB4() {
        controlador = new Controlador();
        initComponents();
        panellReproduccio.add(controlador.getPanel(), BorderLayout.CENTER);
        panellGestioReproduccio.setVisible(false);
        panellCanviNom.setVisible(false);
        panellCanviMida.setVisible(false);
        fotoPubli.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellAnunci = new javax.swing.JPanel();
        fotoPubli = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panellBiblioteca = new javax.swing.JPanel();
        bntAfegirBiblio = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnElimina = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        llistaBiblioteca = new javax.swing.JList<>();
        btnRepro = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        panellGestioAlbums = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnReprodueixAlbum = new javax.swing.JButton();
        btnSuprimeixAlbum = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        llistaAlbums = new javax.swing.JList<>();
        btnAfegeixAlbum = new javax.swing.JButton();
        canviaMida = new javax.swing.JButton();
        panellCanviNom = new javax.swing.JPanel();
        txtTitolAlbum = new javax.swing.JTextField();
        btnCanviaAlbum = new javax.swing.JButton();
        btnEliminaAlbum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaContingutAlbum = new javax.swing.JList<>();
        btnAfegirFitxerAlbum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panellCanviMida = new javax.swing.JPanel();
        btnCanviaMida = new javax.swing.JButton();
        txtCanviMida = new javax.swing.JTextField();
        mostraContingut = new javax.swing.JButton();
        etiquetaContingutAlbums = new javax.swing.JLabel();
        canviaNom = new javax.swing.JButton();
        btnReproFitxerAlbum = new javax.swing.JButton();
        etiquetaContingutAlbum = new javax.swing.JLabel();
        panellGestioReproduccio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAtura = new javax.swing.JButton();
        bntPausa = new javax.swing.JButton();
        btnReempren = new javax.swing.JButton();
        btnSeguent = new javax.swing.JButton();
        panellRepro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        opcioPremium = new javax.swing.JRadioButton();
        btnVisualitza = new javax.swing.JToggleButton();
        reproCiclica = new javax.swing.JRadioButton();
        panellReproduccio = new javax.swing.JPanel();
        btnReproFitxer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panellAnunci.setLayout(new javax.swing.OverlayLayout(panellAnunci));

        fotoPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/RasJimenezBlai/vista/notPremiumPubli.PNG"))); // NOI18N
        panellAnunci.add(fotoPubli);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/RasJimenezBlai/vista/logoNormal.PNG"))); // NOI18N
        panellAnunci.add(jLabel7);

        bntAfegirBiblio.setText("Afegeix");
        bntAfegirBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAfegirBiblioActionPerformed(evt);
            }
        });

        btnRecuperar.setText("Recupera les Dades");
        btnRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecuperarMouseEntered(evt);
            }
        });
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        jLabel1.setText("Bibliteca:");

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guarda les Dades");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(llistaBiblioteca);

        btnRepro.setText("Reprodueix tota la Biblioteca");
        btnRepro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellBibliotecaLayout = new javax.swing.GroupLayout(panellBiblioteca);
        panellBiblioteca.setLayout(panellBibliotecaLayout);
        panellBibliotecaLayout.setHorizontalGroup(
            panellBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellBibliotecaLayout.createSequentialGroup()
                .addGroup(panellBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellBibliotecaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panellBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panellBibliotecaLayout.createSequentialGroup()
                                .addComponent(bntAfegirBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panellBibliotecaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnRepro)))
                .addContainerGap())
        );
        panellBibliotecaLayout.setVerticalGroup(
            panellBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecuperar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panellBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAfegirBiblio)
                    .addComponent(btnElimina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRepro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ub/prog2/RasJimenezBlai/vista/Publi2.PNG"))); // NOI18N

        btnReprodueixAlbum.setText("Reprodueix-lo!");
        btnReprodueixAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReprodueixAlbumActionPerformed(evt);
            }
        });

        btnSuprimeixAlbum.setText("Suprimeix el Fitxer");
        btnSuprimeixAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuprimeixAlbumActionPerformed(evt);
            }
        });

        jScrollPane6.setMaximumSize(new java.awt.Dimension(260, 84));
        jScrollPane6.setMinimumSize(new java.awt.Dimension(260, 84));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(260, 84));
        jScrollPane6.setRequestFocusEnabled(false);

        llistaAlbums.setMaximumSize(new java.awt.Dimension(260, 84));
        llistaAlbums.setMinimumSize(new java.awt.Dimension(260, 84));
        jScrollPane6.setViewportView(llistaAlbums);

        btnAfegeixAlbum.setText("Crea");
        btnAfegeixAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegeixAlbumActionPerformed(evt);
            }
        });

        canviaMida.setText("Canvia la Mida");
        canviaMida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canviaMidaActionPerformed(evt);
            }
        });

        txtTitolAlbum.setText("Introdueix el nom aqui");

        btnCanviaAlbum.setText("Canvia");
        btnCanviaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanviaAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellCanviNomLayout = new javax.swing.GroupLayout(panellCanviNom);
        panellCanviNom.setLayout(panellCanviNomLayout);
        panellCanviNomLayout.setHorizontalGroup(
            panellCanviNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellCanviNomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitolAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanviaAlbum)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panellCanviNomLayout.setVerticalGroup(
            panellCanviNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellCanviNomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panellCanviNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitolAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCanviaAlbum))
                .addContainerGap())
        );

        btnEliminaAlbum.setText("Elimina l'Album");
        btnEliminaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaAlbumActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(259, 131));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(259, 131));

        llistaContingutAlbum.setMaximumSize(new java.awt.Dimension(259, 131));
        llistaContingutAlbum.setMinimumSize(new java.awt.Dimension(259, 131));
        llistaContingutAlbum.setPreferredSize(new java.awt.Dimension(259, 131));
        jScrollPane1.setViewportView(llistaContingutAlbum);

        btnAfegirFitxerAlbum.setText("Afegeix Fitxers");
        btnAfegirFitxerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerAlbumActionPerformed(evt);
            }
        });

        jLabel2.setText("Albums:");

        btnCanviaMida.setText("Canvia");
        btnCanviaMida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanviaMidaActionPerformed(evt);
            }
        });

        txtCanviMida.setText("Introdueix la mida aqui");

        javax.swing.GroupLayout panellCanviMidaLayout = new javax.swing.GroupLayout(panellCanviMida);
        panellCanviMida.setLayout(panellCanviMidaLayout);
        panellCanviMidaLayout.setHorizontalGroup(
            panellCanviMidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellCanviMidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCanviMida, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanviaMida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellCanviMidaLayout.setVerticalGroup(
            panellCanviMidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellCanviMidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panellCanviMidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanviaMida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCanviMida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
        );

        mostraContingut.setText("Mostra el Contingut");
        mostraContingut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraContingutActionPerformed(evt);
            }
        });

        etiquetaContingutAlbums.setText("Contingut del Album: ");

        canviaNom.setText("Canvia el Nom");
        canviaNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canviaNomActionPerformed(evt);
            }
        });

        btnReproFitxerAlbum.setText("Reprodueix el Fitxer Seleccionat");
        btnReproFitxerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproFitxerAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panellCanviMida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(canviaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panellCanviNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAfegirFitxerAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnSuprimeixAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnAfegeixAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnReprodueixAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mostraContingut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(canviaMida, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaContingutAlbums)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiquetaContingutAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnReproFitxerAlbum)
                                .addGap(28, 28, 28)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegeixAlbum)
                            .addComponent(btnEliminaAlbum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReprodueixAlbum)
                            .addComponent(mostraContingut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canviaNom)
                            .addComponent(canviaMida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panellCanviNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panellCanviMida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaContingutAlbums)
                    .addComponent(etiquetaContingutAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuprimeixAlbum)
                    .addComponent(btnAfegirFitxerAlbum))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReproFitxerAlbum)
                .addGap(16, 16, 16))
        );

        jLabel3.setText("Gestió Reproducció");

        btnAtura.setText("Atura");
        btnAtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturaActionPerformed(evt);
            }
        });

        bntPausa.setText("Pause");
        bntPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPausaActionPerformed(evt);
            }
        });

        btnReempren.setText("Reemprèn");
        btnReempren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReemprenActionPerformed(evt);
            }
        });

        btnSeguent.setText("Següent");
        btnSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellGestioReproduccioLayout = new javax.swing.GroupLayout(panellGestioReproduccio);
        panellGestioReproduccio.setLayout(panellGestioReproduccioLayout);
        panellGestioReproduccioLayout.setHorizontalGroup(
            panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellGestioReproduccioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bntPausa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSeguent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReempren, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panellGestioReproduccioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellGestioReproduccioLayout.setVerticalGroup(
            panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellGestioReproduccioLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtura)
                    .addComponent(btnSeguent))
                .addGap(18, 18, 18)
                .addGroup(panellGestioReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPausa)
                    .addComponent(btnReempren)))
        );

        javax.swing.GroupLayout panellGestioAlbumsLayout = new javax.swing.GroupLayout(panellGestioAlbums);
        panellGestioAlbums.setLayout(panellGestioAlbumsLayout);
        panellGestioAlbumsLayout.setHorizontalGroup(
            panellGestioAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellGestioAlbumsLayout.createSequentialGroup()
                .addGroup(panellGestioAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panellGestioReproduccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        panellGestioAlbumsLayout.setVerticalGroup(
            panellGestioAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellGestioAlbumsLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panellGestioReproduccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setText("Reproducció");

        opcioPremium.setSelected(true);
        opcioPremium.setText("Premium");
        opcioPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioPremiumActionPerformed(evt);
            }
        });

        btnVisualitza.setText("Visualitza");
        btnVisualitza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzaActionPerformed(evt);
            }
        });

        reproCiclica.setText("Reproducció Cíclica");
        reproCiclica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproCiclicaActionPerformed(evt);
            }
        });

        panellReproduccio.setLayout(new java.awt.BorderLayout());

        btnReproFitxer.setText("Reprodueix");
        btnReproFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproFitxerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panellReproLayout = new javax.swing.GroupLayout(panellRepro);
        panellRepro.setLayout(panellReproLayout);
        panellReproLayout.setHorizontalGroup(
            panellReproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellReproLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panellReproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellReproLayout.createSequentialGroup()
                        .addComponent(reproCiclica)
                        .addGap(6, 6, 6)
                        .addComponent(opcioPremium))
                    .addComponent(jLabel4)
                    .addGroup(panellReproLayout.createSequentialGroup()
                        .addComponent(btnReproFitxer)
                        .addGap(54, 54, 54)
                        .addComponent(btnVisualitza)))
                .addGap(196, 196, 196))
            .addGroup(panellReproLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panellReproduccio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panellReproLayout.setVerticalGroup(
            panellReproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellReproLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellReproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reproCiclica)
                    .addComponent(opcioPremium))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(panellReproLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualitza)
                    .addComponent(btnReproFitxer))
                .addGap(24, 24, 24)
                .addComponent(panellReproduccio, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panellBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panellGestioAlbums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panellAnunci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panellRepro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panellAnunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panellRepro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panellBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panellGestioAlbums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        MenuGuardar guardar = new MenuGuardar(this, true, controlador);
        guardar.setLocationRelativeTo(null);
        guardar.setTitle("Guarda");
        guardar.setVisible(true);
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturaActionPerformed

        controlador.aturaReproduccio();
    }//GEN-LAST:event_btnAturaActionPerformed

    private void bntAfegirBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAfegirBiblioActionPerformed
        FrmAfegirFitxerMultimedia dialog  = new FrmAfegirFitxerMultimedia(this, true, controlador);
        dialog.setName("Afegir un Fitxer");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        omplirLlistatBiblioteca();
    }//GEN-LAST:event_bntAfegirBiblioActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        if(controlador.getBiblio().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix algun fitxer abans d'esborrar!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            if (llistaBiblioteca.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecciona un fitxer abans d'eliminar-lo!","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                for (Object item: llistaBiblioteca.getSelectedValues()) {
                    try {
                        FitxerMultimedia element = (FitxerMultimedia) item;
                        controlador.esborrarPath(element.getAbsolutePath()); //PHGDOSF
                    } catch (AplicacioException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Error al intentar esborrar el fitxer: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                omplirLlistatBiblioteca();
                omplirContingutAlbum(etiquetaContingutAlbum.getText());
            }
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnVisualitzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzaActionPerformed
        if (controlador.getBiblio().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Afegeix fitxers abans de mostrar una imatge!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            for (Object item: llistaBiblioteca.getSelectedValues()) {
                try{
                    FitxerMultimedia element = (FitxerMultimedia) item;
                    if (element instanceof FitxerReproduible) {
                        JOptionPane.showMessageDialog(rootPane,"Estas intentant visualitzar un Video!","Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                        int pos = controlador.getBiblio().getPos((File) item);
                        controlador.mostrarFitxer(pos, -1);
                        panellGestioReproduccio.setVisible(true);
                    }
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane,"Error al intentar visualitzar la imatge: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnVisualitzaActionPerformed

    private void btnReproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproActionPerformed
        if (controlador.getBiblio().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Afegeix fitxers abans de reproduir la biblioteca!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                panellGestioReproduccio.setVisible(true);
                controlador.reproduirCarpeta();
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error al reproduir tota la biblioteca: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnReproActionPerformed

    private void btnAfegeixAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegeixAlbumActionPerformed
        MenuCrearAlbum dialog = new MenuCrearAlbum(this, true, controlador);
        dialog.setTitle("Crea");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        omplirLlistaAlbums();
    }//GEN-LAST:event_btnAfegeixAlbumActionPerformed

    private void reproCiclicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproCiclicaActionPerformed
        if (reproCiclica.isSelected()) {
            controlador.activarModeCiclic(true);
        } else {
            controlador.activarModeCiclic(false);
        }
    }//GEN-LAST:event_reproCiclicaActionPerformed

    private void opcioPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioPremiumActionPerformed

        controlador.desactivarModePremium();
        fotoPubli.setVisible(true);
        opcioPremium.setEnabled(false);
    }//GEN-LAST:event_opcioPremiumActionPerformed

    private void bntPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPausaActionPerformed
        controlador.pausaReproduccio();
    }//GEN-LAST:event_bntPausaActionPerformed

    private void btnReemprenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReemprenActionPerformed
        controlador.reemprenReproduccio();
    }//GEN-LAST:event_btnReemprenActionPerformed

    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed
        try {
            controlador.saltaReproduccio();
        } catch (AplicacioException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar reproduir el seguent arxiu: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeguentActionPerformed

    private void canviaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canviaNomActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de canviar-li el nom!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            panellCanviNom.setVisible(true);
        }
    }//GEN-LAST:event_canviaNomActionPerformed

    private void btnCanviaMidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanviaMidaActionPerformed

        for(Object item:  llistaAlbums.getSelectedValues()){
                AlbumFitxersMultimedia elementSeleccionat = (AlbumFitxersMultimedia) item;
                try {
                    int mida = Integer.parseInt(txtCanviMida.getText());
                    controlador.canviarMidaAlbum(elementSeleccionat.getTitol(), mida);
                    panellCanviMida.setVisible(true);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al canivar la mida del Album: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
        }
        omplirLlistaAlbums();
        panellCanviMida.setVisible(false);
    }//GEN-LAST:event_btnCanviaMidaActionPerformed

    private void btnCanviaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanviaAlbumActionPerformed
        String nouTitol = txtTitolAlbum.getText();
        for (Object item: llistaAlbums.getSelectedValues()) {
            AlbumFitxersMultimedia elementSel = (AlbumFitxersMultimedia) item;
            try {
                controlador.canviarTitolAlbum(elementSel.getTitol(), nouTitol);
                panellCanviNom.setVisible(false);
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error al canivar el titol del Album: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        omplirLlistaAlbums();
        etiquetaContingutAlbum.setText(nouTitol);
        panellCanviNom.setVisible(false);
    }//GEN-LAST:event_btnCanviaAlbumActionPerformed

    private void canviaMidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canviaMidaActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de canviar-li la mida!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            panellCanviMida.setVisible(true);
        }
    }//GEN-LAST:event_canviaMidaActionPerformed

    private void btnAfegirFitxerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerAlbumActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans d'afegir-li contingut!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            if (controlador.getBiblio().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Afegeix elements a la biblioteca abans d'afegir contingut a un album!","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                if (llistaAlbums.getSelectedIndex() == -1) {
                    JOptionPane.showMessageDialog(rootPane, "Selecciona un Album a afegir-li fitxers!","Atencio",JOptionPane.WARNING_MESSAGE);
                }else{
                    for (Object item: llistaAlbums.getSelectedValues()) {
                        AlbumFitxersMultimedia album = (AlbumFitxersMultimedia) item;
                        seleccioFitxersAfegir menu = new seleccioFitxersAfegir(this, true, controlador,album);
                        menu.setLocationRelativeTo(null);
                        menu.setTitle("Afegeix");
                        menu.setVisible(true);
                        if (controlador.getAlbums().isEmpty()) {
                            System.out.println("IOSHDFIOUJASGBDFSÔAIUGBDFASO*UGDASOu");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAfegirFitxerAlbumActionPerformed

    private void mostraContingutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraContingutActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de mostrar el seu contingut!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            if (llistaAlbums.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecciona un album abans de mostrar el seu contingut!","Atencio",JOptionPane.INFORMATION_MESSAGE);
            } else {
                int pos = llistaAlbums.getSelectedIndex();
                DefaultListModel model = new DefaultListModel();
                model.clear();
                AlbumFitxersMultimedia album = controlador.getAlbums().get(pos);
                List<String> llista;
                try {

                    llista = controlador.mostrarAlbum(album.getTitol());
                    Iterator itr = llista.iterator();
                    while (itr.hasNext()) {
                        model.addElement(itr.next());
                    }
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "No s'ha pogut mostrar el contingut del Album "+album.getTitol()+" : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
                llistaContingutAlbum.setModel(model);
                etiquetaContingutAlbum.setText(album.getTitol());
            }
        }
    }//GEN-LAST:event_mostraContingutActionPerformed

    
    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        MenuRecuperar recuperar = new MenuRecuperar(this, true, controlador);
        recuperar.setTitle("Recupera");
        recuperar.setLocationRelativeTo(null);
        recuperar.setVisible(true);
        omplirLlistatBiblioteca();
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void btnSuprimeixAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuprimeixAlbumActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de suprimir un fitxer contingut!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            int pos = llistaContingutAlbum.getSelectedIndex();
            try {
                controlador.esborrarFitxer(etiquetaContingutAlbum.getText(), pos);
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(rootPane, "No s'ha pogut eliminar l'Album "+etiquetaContingutAlbum.getText()+" : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            omplirContingutAlbum(etiquetaContingutAlbum.getText());
        }
    }//GEN-LAST:event_btnSuprimeixAlbumActionPerformed

    private void btnEliminaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaAlbumActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Afegeix algun album abans d'esborrar!","Error",JOptionPane.ERROR_MESSAGE);
        } else {                                      
            for (Object item: llistaAlbums.getSelectedValues()) {
                AlbumFitxersMultimedia album = (AlbumFitxersMultimedia) item;
                try {
                    controlador.esborrarAlbum(album.getTitol());
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "No s'ha pogut esborrar l'album: "+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
                }
            }
            omplirLlistaAlbums();
        }
    }//GEN-LAST:event_btnEliminaAlbumActionPerformed

    private void btnReprodueixAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprodueixAlbumActionPerformed
        if (controlador.getAlbums().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de reproduir-lo!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            int pos = llistaAlbums.getSelectedIndex();
            AlbumFitxersMultimedia album = controlador.getAlbums().get(pos);
            if (album.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "L'album esta buit!", "Atencio",JOptionPane.WARNING_MESSAGE);
            }else{
                try {
                    controlador.reproduirCarpeta(album.getTitol());
                    panellGestioReproduccio.setVisible(true);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "No s'ha pogut reproduir l'Album "+album.getTitol()+" : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnReprodueixAlbumActionPerformed

    private void btnReproFitxerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproFitxerAlbumActionPerformed

        if (controlador.getAlbums().isEmpty())  {
            JOptionPane.showMessageDialog(rootPane, "Afegeix un album abans de reproduir un fitxer contingut!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            if (llistaContingutAlbum.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecciona abans un fitxer a reproduir!","Error",JOptionPane.ERROR_MESSAGE);
            } else {
                
                int id = llistaContingutAlbum.getSelectedIndex();
                int posAlbum = controlador.getAlbumIndex(etiquetaContingutAlbum.getText());
                
                FitxerMultimedia fitxer = (FitxerMultimedia) controlador.getAlbums().get(posAlbum).getAt(id);
                
                try {
                    controlador.reproduirFitxerAlbum(fitxer);
                    panellGestioReproduccio.setVisible(true);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar reproduir el fitxer: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnReproFitxerAlbumActionPerformed

    private void btnReproFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproFitxerActionPerformed
        if (controlador.getBiblio().isEmpty())  {
            JOptionPane.showMessageDialog(rootPane, "Afegeix algun fitxer abans de reproduir-lo","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            if(llistaBiblioteca.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Selecciona un fitxer abans de reproduir-lo","Atenció",JOptionPane.INFORMATION_MESSAGE);
            } else {
                int id = llistaBiblioteca.getSelectedIndex()+1;
                try {
                    controlador.reproduirFitxer(id);
                    panellGestioReproduccio.setVisible(true);
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar reproduir el fitxer: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnReproFitxerActionPerformed

    private void btnRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecuperarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AplicacioUB4 app = new AplicacioUB4();
                app.setLocationRelativeTo(null);
                app.setTitle("Reproductor Multimedia d'en Blai");
                app.setVisible(true);
            }
        });
    }
    
    public void omplirLlistatBiblioteca() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for (FitxerMultimedia item: controlador.getBiblio().getLlista()){
            model.addElement(item);
            
        }
        llistaBiblioteca.setModel(model);
    }
    
    private void omplirLlistaAlbums() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(AlbumFitxersMultimedia item: controlador.getAlbums()){
            model.addElement(item);
        }
        llistaAlbums.setModel(model);
    }
    
    private void buidarLlistaAlbums() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        llistaAlbums.setModel(model);
    }
    
    private void omplirContingutAlbum(String titol) {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        List<String> llista;
        if (!titol.equals("")) {
            try {
                llista = controlador.mostrarAlbum(titol);
                Iterator itr = llista.iterator();
                while (itr.hasNext()) {
                    model.addElement(itr.next());
                }
            } catch (AplicacioException ex) {
                JOptionPane.showMessageDialog(rootPane, "No s'ha pogut mostrar el contingut del Album "+titol+" : "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            llistaContingutAlbum.setModel(model);
        } else {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAfegirBiblio;
    private javax.swing.JButton bntPausa;
    private javax.swing.JButton btnAfegeixAlbum;
    private javax.swing.JButton btnAfegirFitxerAlbum;
    private javax.swing.JButton btnAtura;
    private javax.swing.JButton btnCanviaAlbum;
    private javax.swing.JButton btnCanviaMida;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnEliminaAlbum;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JButton btnReempren;
    private javax.swing.JToggleButton btnRepro;
    private javax.swing.JButton btnReproFitxer;
    private javax.swing.JButton btnReproFitxerAlbum;
    private javax.swing.JButton btnReprodueixAlbum;
    private javax.swing.JButton btnSeguent;
    private javax.swing.JButton btnSuprimeixAlbum;
    private javax.swing.JToggleButton btnVisualitza;
    private javax.swing.JButton canviaMida;
    private javax.swing.JButton canviaNom;
    private javax.swing.JLabel etiquetaContingutAlbum;
    private javax.swing.JLabel etiquetaContingutAlbums;
    private javax.swing.JLabel fotoPubli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> llistaAlbums;
    private javax.swing.JList<String> llistaBiblioteca;
    private javax.swing.JList<String> llistaContingutAlbum;
    private javax.swing.JButton mostraContingut;
    private javax.swing.JRadioButton opcioPremium;
    private javax.swing.JPanel panellAnunci;
    private javax.swing.JPanel panellBiblioteca;
    private javax.swing.JPanel panellCanviMida;
    private javax.swing.JPanel panellCanviNom;
    private javax.swing.JPanel panellGestioAlbums;
    private javax.swing.JPanel panellGestioReproduccio;
    private javax.swing.JPanel panellRepro;
    private javax.swing.JPanel panellReproduccio;
    private javax.swing.JRadioButton reproCiclica;
    private javax.swing.JTextField txtCanviMida;
    private javax.swing.JTextField txtTitolAlbum;
    // End of variables declaration//GEN-END:variables
}


