/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.RasJimenezBlai.vista;

import edu.ub.prog2.RasJimenezBlai.controlador.Controlador;
import edu.ub.prog2.RasJimenezBlai.model.AlbumFitxersMultimedia;
import edu.ub.prog2.RasJimenezBlai.model.FitxerMultimedia;
import edu.ub.prog2.utils.AplicacioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author blrasjim7.alumnes
 */
public class seleccioFitxersAfegir extends javax.swing.JDialog {
    AlbumFitxersMultimedia albumaAfegir;
    Controlador controlador;
    /**
     * Creates new form seleccioFitxersAfegir
     */
    public seleccioFitxersAfegir(java.awt.Frame parent, boolean modal, Controlador controlador, AlbumFitxersMultimedia album) {
        super(parent, modal);
        this.controlador = controlador;
        this.albumaAfegir = album;
        initComponents();
        omplirLlista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        llistaBiblio = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnAfegirAlbumFitxers = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(llistaBiblio);

        jLabel1.setText("Selecciona el fitxer a Afegir:");

        btnAfegirAlbumFitxers.setText("Afegeix");
        btnAfegirAlbumFitxers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirAlbumFitxersActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnAfegirAlbumFitxers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancela)
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegirAlbumFitxers)
                    .addComponent(btnCancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void omplirLlista() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for (FitxerMultimedia item: controlador.getBiblio().getLlista()){
            model.addElement(item);
        }
        llistaBiblio.setModel(model);
    
    }
    
    private void btnAfegirAlbumFitxersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirAlbumFitxersActionPerformed
        if (llistaBiblio.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un fitxer a afegir", "Atencio", JOptionPane.WARNING_MESSAGE);
        } else {
            for (Object item: llistaBiblio.getSelectedValues()) {
                FitxerMultimedia fitxer = (FitxerMultimedia) item;
                try {
                    albumaAfegir.addFitxer(fitxer);
                    this.dispose();
                } catch (AplicacioException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar afegir un fitxer: "+ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAfegirAlbumFitxersActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirAlbumFitxers;
    private javax.swing.JButton btnCancela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> llistaBiblio;
    // End of variables declaration//GEN-END:variables
}
